// Isolated browser smoke test. Never writes accounts into the real application DB.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const managed = process.env.KARIGARPAY_NODE_WORKSPACE || 'C:/Users/Prakh/.workbuddy-ai/binaries/node/workspace';
const require = createRequire(join(managed, 'package.json'));
const { chromium } = require('playwright');
const python = process.env.KARIGARPAY_TEST_PYTHON || 'C:/Users/Prakh/.workbuddy-ai/binaries/python/envs/karigarpay/Scripts/python.exe';
const output = join(root, 'outputs');
await mkdir(output, { recursive: true });
const data = await mkdtemp(join(output, 'browser-test-'));
const server = spawn(python, [join(root, 'main.py'), '--port', '8001'], { cwd: root, env: { ...process.env, KARIGARPAY_DB: join(data, 'test.db'), KARIGARPAY_UPLOADS: join(data, 'photos'), KARIGARPAY_ORIGINS: 'http://localhost:8001,http://127.0.0.1:8001', KARIGARPAY_HOSTS: 'localhost,127.0.0.1', KARIGARPAY_ENV: 'development' }, stdio: ['ignore', 'pipe', 'pipe'] });
let outputLog = '';
let readyResolve, readyReject;
const ready = new Promise((res, rej) => { readyResolve = res; readyReject = rej; });
const timeout = setTimeout(() => readyReject(new Error('Test server startup timed out: ' + outputLog)), 20000);
for (const stream of [server.stdout, server.stderr]) stream.on('data', chunk => { outputLog += chunk.toString(); if (outputLog.includes('Uvicorn running')) { clearTimeout(timeout); readyResolve(); } });
server.on('exit', code => { if (code) readyReject(new Error('Server exited: ' + outputLog)); });
let browser;
const errors = [], checks = [];
const note = text => { checks.push(text); console.log('PASS', text); };
async function nav(page, hash, selector) { await page.evaluate(hash => { location.hash = hash; }, hash); await page.locator(selector).first().waitFor({ state: 'visible' }); }
async function uiSubmit(page, form, apiPath, action = null) {
  const res = page.waitForResponse(r => r.url().includes(apiPath) && r.request().method() !== 'GET');
  if (action) await action(); else await page.locator(`${form} button[type="submit"]`).click();
  const response = await res;
  assert.ok(response.ok(), `${apiPath} ${response.status()}: ${await response.text()}`);
  return await response.json();
}
try {
  await ready;
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  const page = await ctx.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error' && !m.text().includes('401 (Unauthorized)')) errors.push(m.text()); });
  await page.goto('http://localhost:8001');
  await page.locator('#auth-form').waitFor();
  await page.screenshot({ path: join(output, 'KarigarPay-welcome.png'), fullPage: true });
  assert.equal(await page.locator('#auth-form').count(), 1); note('Welcome screen renders without runtime errors');
  await page.locator('[data-action="auth-mode"][data-mode="register"]').click();
  await page.locator('#auth-form [name="name"]').fill('Sharma Garments & Packaging');
  await page.locator('#auth-form [name="owner_name"]').fill('Prakhar Sharma');
  await page.locator('#auth-form [name="owner_phone"]').fill('9876543210');
  await page.locator('#auth-form [name="pin"]').fill('1248');
  const registered = await uiSubmit(page, '#auth-form', '/auth/register');
  await page.locator('.stats-grid').waitFor();
  assert.match(registered.business.id, /^BIZ-/); note('Owner registration and live dashboard');
  await nav(page, 'workers', '[data-action="worker-add"]');
  await page.locator('[data-action="worker-add"]').first().click();
  await page.locator('#worker-form [name="name"]').fill('Ramesh Kumar');
  await page.locator('#worker-form [name="phone"]').fill('9876543211');
  await page.locator('#worker-form [name="worker_pin"]').fill('2468');
  await page.locator('#worker-form [name="upi_id"]').fill('ramesh@upi');
  const worker = await uiSubmit(page, '#worker-form', '/workers');
  await page.locator('#modal').waitFor({ state: 'hidden' });
  await page.locator(`[data-action="worker-edit"][data-id="${worker.id}"]`).waitFor(); note('Worker creation and tenant code');

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const wp = await mobile.newPage();
  wp.on('pageerror', e => errors.push('Worker: ' + e.message));
  await wp.goto('http://localhost:8001');
  await wp.locator('[data-action="auth-role"][data-role="worker"]').click();
  await wp.locator('#auth-form [name="business_id"]').fill(registered.business.id);
  await wp.locator('#auth-form [name="phone"]').fill('9876543211');
  await wp.locator('#auth-form [name="pin"]').fill('2468');
  await uiSubmit(wp, '#auth-form', '/auth/login');
  await wp.locator('#entry-form').waitFor();
  await wp.locator('#transcript').fill('Aaj 10 dozen packing kiya aur 2 ghante overtime kiya');
  await wp.locator('[data-action="apply-transcript"]').click();
  assert.equal(await wp.locator('#entry-form [name="quantity"]').inputValue(), '10');
  assert.equal(await wp.locator('#entry-form [name="ot_hours"]').inputValue(), '2');
  assert.match(await wp.locator('#entry-form [name="task_id"] option:checked').innerText(), /Packing/);
  await wp.screenshot({ path: join(output, 'KarigarPay-worker-mobile.png'), fullPage: true });
  assert.ok((await wp.locator('#entry-form').innerText()).includes('Packing'));
  note('Mobile worker sign-in and Hinglish draft filling');
  // Language must change immediately without losing the transcript or entry.
  await wp.locator('.topbar [data-action="language"]').click();
  assert.equal(await wp.locator('html').getAttribute('lang'), 'hi');
  assert.equal(await wp.locator('#transcript').inputValue(), 'Aaj 10 dozen packing kiya aur 2 ghante overtime kiya');
  await wp.locator('.topbar [data-action="language"]').click();
  assert.equal(await wp.locator('html').getAttribute('lang'), 'en');
  note('Hindi/English switch preserves unsaved work');
  await wp.locator('#entry-form button[type="submit"]').click();
  const submitted = await uiSubmit(wp, '#entry-confirm-form', '/submissions');
  assert.equal(submitted.base, 150); assert.equal(submitted.overtime, 100); assert.equal(submitted.total, 250);
  await wp.locator('#modal').waitFor({state:'hidden'});
  note('Worker work submission calculates INR250 on server');

  await nav(page, 'review', '[data-action="review-entry"]');
  await page.locator(`[data-action="review-entry"][data-id="${submitted.id}"]`).click();
  await page.locator('#review-entry-form button[value="approve"]').click();
  const approved = await uiSubmit(page, '#confirm-form', `/submissions/${submitted.id}/review`);
  assert.equal(approved.status, 'approved');
  await page.locator('#modal').waitFor({state:'hidden'}); note('Owner review and explicit approval');
  await nav(page, 'advances', '[data-action="advance-add"]');
  await page.locator('[data-action="advance-add"]').first().click();
  await page.locator('#advance-form [name="amount"]').fill('50');
  await page.locator('#advance-form [name="note"]').fill('Groceries');
  await page.locator('#advance-form [name="confirmed"]').check();
  await uiSubmit(page, '#advance-form', '/advances');
  await page.locator('#modal').waitFor({state:'hidden'}); note('Advance recording');
  await nav(page, 'payroll', '[data-action="pay-preview"]');
  await page.locator(`[data-action="pay-preview"][data-id="${worker.id}"]`).click();
  await page.locator('#settlement-form').waitFor();
  const qr = page.locator('#modal img[alt="UPI payment QR code"]');
  await qr.waitFor();
  await page.waitForFunction(() => { const i = document.querySelector('#modal img'); return i && i.complete && i.naturalWidth > 0; });
  assert.ok((await page.locator('#modal').innerText()).includes('₹200'));
  await page.screenshot({ path: join(output, 'KarigarPay-payroll.png'), fullPage: true });
  await page.locator('#settlement-form [name="confirmed"]').check();
  const paid = await uiSubmit(page, '#settlement-form', '/settlements');
  assert.equal(paid.net, 200); assert.equal(paid.method, 'cash');
  note('Salary slip, dynamic UPI QR and cash settlement INR200');
  await page.locator('#modal [data-action="close-modal"]').click();
  await nav(page, 'overview', '.stats-grid');
  await page.screenshot({ path: join(output, 'KarigarPay-owner-desktop.png'), fullPage: true });
  await nav(wp, 'slips', '[data-action="view-slip"]');
  assert.ok((await wp.locator('#main').innerText()).includes('₹200'));
  note('Settled receipt visible in worker account');
  const overflow = await wp.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  assert.equal(overflow, false); note('No 390px mobile horizontal overflow');
  await wp.setViewportSize({width:360,height:800});
  await nav(wp, 'home', '.worker-hero');
  assert.equal(await wp.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1), false);
  note('No 360px worker horizontal overflow');
  await wp.evaluate(() => navigator.serviceWorker.ready);
  const cached = await wp.evaluate(async () => { const keys = await caches.keys(); const urls=[]; for(const key of keys) for(const r of await (await caches.open(key)).keys()) urls.push(new URL(r.url).pathname); return urls; });
  assert.ok(cached.includes('/static/app.js')); assert.equal(cached.some(p => p.startsWith('/api')), false);
  note('PWA caches public shell only, never wage records');
  const before = await wp.evaluate(() => Object.keys(localStorage));
  assert.deepEqual(before, ['karigarpay-language']); note('No auth tokens or wages in persistent browser storage');
  await mobile.setOffline(true);
  await wp.locator('#connection-status .offline-banner').waitFor();
  assert.match(await wp.locator('#connection-status').innerText(), /offline/); note('Offline notice is explicit');
  await mobile.setOffline(false);
  await ctx.close(); await mobile.close();
  assert.deepEqual(errors, [], 'Browser console/runtime errors: ' + errors.join('\n'));
  await writeFile(join(output, 'browser-test-results.json'), JSON.stringify({passed:checks.length,checks,errors},null,2));
  console.log(`Browser E2E checks passed: ${checks.length}`);
} catch (error) {
  console.error(error);
  await writeFile(join(output, 'browser-test-failure.txt'), String(error) + '\n' + outputLog);
  if (browser) for (const ctx of browser.contexts()) for (const [index, p] of ctx.pages().entries()) await p.screenshot({path:join(output, `failure-${ctx===browser.contexts()[0]?'owner':'worker'}-${index}.png`), fullPage:true}).catch(()=>{});
  process.exitCode = 1;
} finally {
  if (browser) await browser.close();
  server.kill();
  clearTimeout(timeout);
}
